### PR TITLE
Permission Groups

### PR DESCRIPTION
**Pull request by JEK0x81D**
#10

### CODE REVIEW

**Comment by va1kio** [comment]
the UI.rbxmx there seems to be an old version, are you able to merge with the new one?

**Comment by JEK0x81D** [comment]
> 
> 
> the UI.rbxmx there seems to be an old version, are you able to merge with the new one?

I've resolved it for now. If you take a look at the init file you can see where I fired the event that sends the rank, if you could implement it into your UI when you get a chance that would be great.

**Comment by JEK0x81D** [comment]
> 
> 
> the UI.rbxmx there seems to be an old version, are you able to merge with the new one?

Scratch that, apparently my git client didn't apply the changes. One moment.

**Comment by va1kio** [comment]
Yeah, apparently it was malformed 
image

**Comment by JEK0x81D** [comment]
> 
> 
> Yeah, apparently it was malformed
> image

Should be all good now. In the future it may be beneficial to abstract the UI logic outside of the model, allowing for contributors to at least make changes to the script part of it.

**Comment by va1kio** [comment]
Will do.

**Pull request merged**
