### PR TITLE
Un-freeze by heal

### PR DESCRIPTION
**Pull request by RigidStudios**
It would make sense for it to unfreeze/make the state of the player "better" when healed.

### CODE REVIEW

**Comment by va1kio** [comment]
I don't see a lot of points in incorporating the "thaw" feature into the heal command. Considering that command is solely for setting the user's health to the MaxHealth value.

**Comment by RigidStudios** [comment]
Thaw is harder to find and not the first thing I thought of to unfreeze, I would've gone directly for 'unfreeze', so either an alias system or this for simplicity in my opinion.

**Comment by va1kio** [comment]
Hm, I'll probably rename Thaw to Unfreeze in DP2 A1151

**Comment by va1kio** [comment]
By the way, it is recommended to merge commit into preview branch, the main branch is only for GM.

**Pull request closed without merging**
