### PR TITLE
Create Explode.lua

### PR DESCRIPTION
**Pull request by ccuser44**
Added an explode command

### CODE REVIEW

**Comment by va1kio** [comment]
Congratulations on your first pull request in this repository! However, we are sorry that we will be denying this pull request. Commander is designed and built solely for moderation purposes, not for all-in-one solution (Debugging, Moderation, Fun). While this command may seem to be a moderation-based command. In fact, it is not. (excessive and unnecessary effects which may ruin the overall gameplay experience)

However, if you happen to own a Discord account (legally) and can join a server (also legally), feel free to submit this command as a custom package in our Discord community, the link can be found on our website.

**Comment by va1kio** [comment]
By the way, .GetCharacter method checks for the existence of Humanoid and HumanoidRootPart, there is no need to do a :FindFirstChild on HumanoidRootPart. Just use Character.PrimaryPart!

**Comment by ccuser44** [comment]
Yeah I might join the discord.

**Comment by ccuser44** [comment]
Yeah I might make a repo for extra commands. Does that sound a good idea?

**Pull request closed without merging**
