### PR TITLE
Made systemmessage and message server commands. And added notify command.

### PR DESCRIPTION
**Pull request by ccuser44**
Now they will be displayed to all players. Normally all admin commands display them to everyone and it is a bit cumbersome to specify the players to them. Private message exists when you want to communicate to spesific players.

### CODE REVIEW

**Comment by va1kio** [comment]
This would be problematic if people want to message/hint a specific group of people. Let's say if someone want to send a hint to all the administrators.

**Comment by ccuser44** [comment]
Well maybe. But system message atleast should be a server command. There is no reason why you would want to display a system message to only spesific players.


In 99% of the cases people want the messages to be displayed to everyone. And every other admin command displays them to everyone so people might accidentally get confused and type the message where they should type the player names.


And the PrivateMessage command serves the purpose of Message and SystemMessage perfectly so there is no reason why they should remain as PlayerCommands.

But I do agree that you may wan't to display a hint to certain players. But maybe we should add some other command which would act like Hint but where you can specify the player.

**Comment by va1kio** [comment]
?! Private messages allows replying, what if the user do not want recipients to be able to reply?

**Comment by ccuser44** [comment]
Hmm.. yeah that is a concern. Maybe we should add a command called "Notify" which would have the same behavior as message but you can specify the player.

**Comment by ccuser44** [comment]
yeah I think I will do that right now. Anyways let me known what you think ;)

**Comment by ccuser44** [comment]
Ok done.
I added a command called "Notify" it has the same behavior as the previous message command

**Comment by ccuser44** [comment]
But what should I do about Hint?

**Comment by ccuser44** [comment]
Ok I will just revert the changes I did on the hint command and decide later what to do.

**Comment by ccuser44** [comment]
Also decided to revet the Hint changes.

So In this pull I made message and systemmessage server commands and added notify which replicates old message.

**Comment by va1kio** [comment]
You should use the API method .notify for this, which does not provide any callback when user is finished interacting

**Comment by ccuser44** [comment]
Ok done.

**Pull request merged**
